name: Build Palmslave BMP

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    # 前回の修正（ghcr.io）はそのまま維持してください
    container: ghcr.io/qmk/qmk_cli:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build Firmware
      # -e オプションを削除しました（rules.mkに書いたため）
      run: qmk compile -kb takashicompany/palmslave -km my_combo

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: palmslave_bmp_firmware
        path: |
          *.hex
          *.uf2
