name: Build Palmslave BMP

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    # 【修正箇所】以前の qmkfm/qmk_build は廃止されたため、こちらを使います
    container: ghcr.io/qmk/qmk_cli:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build Firmware
      # 変更なし
      run: qmk compile -kb takashicompany/palmslave -km my_combo -e CONVERT_TO=promicro_nrf52

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: palmslave_bmp_firmware
        path: |
          *.hex
          *.uf2
